### ISSUE TITLE
Missing undo button under marker

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/unit-rates#232]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0

**Browser**
Safari 18.0

**Problem description**
For https://github.com/phetsims/qa/issues/1151, on the Shopping Lab screen, if I add in values on the number line BEFORE adding anything to the scale, a reset button appears below the marker in the published version but not in the current version. Was this an intentional change?

**Steps to reproduce**
1. On the Shopping Lab Screen, fill in the boxes with the same number for apples and dollars to create a marker in the Double Number Line accordion panel 
2. Repeat the above in the Published version

**Visuals**
<img width="1192" alt="Screenshot 2024-10-10 at 10 31 43 AM" src="https://github.com/user-attachments/assets/d1c69537-09d0-4c5c-be77-221a6ce26150">

<img width="1192" alt="Screenshot 2024-10-10 at 10 31 21 AM" src="https://github.com/user-attachments/assets/2638c23c-3983-42d1-ab79-80fb5311b27d">

**Comment by Nancy-Salpepi** [comment]
This also happens on the Racing Lab screen:
<img width="1027" alt="Screenshot 2024-10-10 at 10 45 55 AM" src="https://github.com/user-attachments/assets/62669faa-3d85-4e38-922c-b998af2e4ee4">
<img width="1027" alt="Screenshot 2024-10-10 at 10 46 03 AM" src="https://github.com/user-attachments/assets/d4380285-8f8e-4d68-a38b-361f120c8c26">

**Comment by pixelzoom** [comment]
Reproduced as @Nancy-Salpepi described above.   I don't recall this being an intentional change, so I'll investigate.

**Comment by pixelzoom** [comment]
This is also a problem on the Shopping screen. For example, for Pears enter 2.00/5 using the marker editor.  In the published version, a reset button will appear under the marker.  In main and 1.1, there is no reset button.

So... The behavior has changed for all 3 screens.

**Comment by pixelzoom** [comment]
Looking in the code, this is actually an undo button.  So I changed the issue title accordingly.

In DoubleNumberLineAccordionBox.ts:

```ts
import undoSolidShape from '../../../../sherpa/js/fontawesome-5/undoSolidShape.js';
...

    // Pressing the undo button moves the marker edit back to its home position,
    // or removes the marker that was most recently added using the editor.
    const undoButton = new RectangularPushButton( {
      content: new Path( undoSolidShape, {
```

**Comment by pixelzoom** [comment]
This problem was introduced between [1.1.0-dev.6](https://phet-dev.colorado.edu/html/unit-rates/1.1.0-dev.6/phet/unit-rates_all_phet.html) on 2/13/24 and [1.1.0-dev.7](https://phet-dev.colorado.edu/html/unit-rates/1.1.0-dev.7/phet/unit-rates_all_phet.html) on 7/5/24.  

There were 27 commits to the unit-rates repo over that period.

The undoButton is in DoubleNumberLineAccordionBox, and there were only 2 commits during that period, neither of which looks relevant.

**Comment by pixelzoom** [comment]
I inspected all of the commits (twice!) for the period where the problem was introduced, and I don't see anything relevant. Perplexing...

**Comment by pixelzoom** [comment]
@marlitas volunteered to be a second set of eyes on this - thanks!  

I added some `console.log` output to DoubleNumberLineAccordionBox, as shown in this patch:

<details>
<summary> DoubleNumberLineAccordionBox  patch</summary>

```diff
Subject: [PATCH] workaround for https://github.com/phetsims/sun/issues/904
---
Index: js/common/view/DoubleNumberLineAccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/DoubleNumberLineAccordionBox.ts b/js/common/view/DoubleNumberLineAccordionBox.ts
--- a/js/common/view/DoubleNumberLineAccordionBox.ts	(revision 96415a7234d51164f754a53135738d3fd617dcf3)
+++ b/js/common/view/DoubleNumberLineAccordionBox.ts	(date 1729635430762)
@@ -33,6 +33,7 @@
 import PickOptional from '../../../../phet-core/js/types/PickOptional.js';
 import { optionize4 } from '../../../../phet-core/js/optionize.js';
 import KeypadLayer from './KeypadLayer.js';
+import Multilink from '../../../../axon/js/Multilink.js';
 
 type SelfOptions = {
   titleStringProperty?: TReadOnlyProperty<string>; // title displayed next to the expand/collapse button
@@ -175,10 +176,15 @@
 
           // Return the marker editor to its home position.
           // Do this before adding the marker so that the undo button is associated with the marker.
+          assert && assert( numerator === markerEditor.numeratorProperty.value );
+          assert && assert( denominator === markerEditor.denominatorProperty.value );
+          console.log( `before resetting markerEditor ${numerator}/${denominator}` );
           markerEditor.reset();
+          console.log( `after resetting markerEditor ${markerEditor.numeratorProperty.value}/${markerEditor.denominatorProperty.value}` );
 
           // add marker to double number line
           if ( doubleNumberLine.addMarker( marker ) ) {
+            console.log( `setting undoMarker ${marker}` );
 
             // allow the new marker to be undone
             doubleNumberLine.undoMarkerProperty.value = marker;
@@ -288,8 +294,14 @@
         }
       }
     };
-    markerEditor.numeratorProperty.link( markerEditorObserver );
-    markerEditor.denominatorProperty.link( markerEditorObserver );
+    markerEditor.numeratorProperty.link( ( numerator, oldNumerator ) => {
+      console.log( `numerator changed, ${oldNumerator} => ${numerator}` );
+      markerEditorObserver();
+    } );
+    markerEditor.denominatorProperty.link( ( denominator, oldDenominator ) => {
+      console.log( `denominator changed, ${oldDenominator} => ${denominator}` );
+      markerEditorObserver();
+    } );
     markerEditorAnimationEnabled = true;
 
     // Observe the 'undo' marker. One level of undo is supported, and the undo button is overloaded.
```

</details>

Then we did these steps:
1. Start the sim
2. Go to the Shopping screen
3. Set the lower-left combo box to "Pears", since we know it's unit rate is $2.00/5.
4. In the marker editor, enter 2 for the numerator.
5. In the marker editor, enter 5 for the denominator.

... and at that point, `markerEditor.reset` is executed, which set its numerator and denominator to null.

The console output was as follows - I've manually added line numbers here, so I can refer to them:

> 1. numerator changed, null => 2
> 2. denominator changed, null => 5
> 3. before resetting markerEditor 2/5
> 4. numerator changed, 2 => null
> 5. after resetting markerEditor null/null
> 6. setting undoMarker Marker[ rate=2/5 creator=editor isMajor=true erasable=true ]
> 7. denominator changed, 5 => null

The console output is not in the expected order.  Line 7 was expected after line 4, since resetting the marker editor resets both its numerator and denominator to null.  And notice that in line 5, both the numerator and denominator have been reset to null, but the observer for the denominator has not fired.  

I'm starting to suspect that something about notification order has changed in axon.

The next thing I'm going to do is checkout shas for 1.1.0-dev.6 (the last working version), apply the above patch for `console.log` output, follow the above steps, and see if the console output is in a different order.

**Comment by pixelzoom** [comment]
Apparently there's no grunt task to checkout a specific version. I wrote a shell script (see below) using the dependencies and shas in https://phet-dev.colorado.edu/html/unit-rates/1.1.0-dev.6/phet/dependencies.json.  After running the script, I needed to restart my transpiler.

After checking out these shas, I verified that the undo button behaves properly, as it does in published 1.1.0-dev.6.

<details>
<summary>checkout-unit-rates-1.1.0-dev.6.sh</summary>

```sh
!/bin/sh
# unit-rates 1.1.0-dev.6 Mon Feb 12 2024 19:27:45 GMT-0700 (Mountain Standard Time)

GITROOT=/Users/cmalley/PhET/GitHub

cd $GITROOT/assert; git checkout dd61947e1ba2c0655a242bebad9b887b397b01dd
cd $GITROOT/axon; git checkout 075c5a61434380dc206e52b4b57eabb1e797494d
cd $GITROOT/brand; git checkout 5e614c8d6309de200bd9166991cf395c16865cfe
cd $GITROOT/chipper; git checkout cde137290887cf9e230536447213e858fd443ef4
cd $GITROOT/dot; git checkout 52c57f59729b480115b9f2e0b579c5a281eba29e
cd $GITROOT/joist; git checkout 55930fbd1787868915d895e23645a2afedd9bc4e
cd $GITROOT/kite; git checkout bb6d7e60fc313e358b17861efce2054c78d74ed6
cd $GITROOT/perennial-alias; git checkout 31500e622ab44154dd93c6078649f0e21cdfc856
cd $GITROOT/phet-core; git checkout da246bbf0c16cc2d1e0d2edbdb17f39255802ccf
cd $GITROOT/phet-io; git checkout 617037c0225c381c76513e0ee5c32a50ca33c4db
cd $GITROOT/phet-io-sim-specific; git checkout 3afded76b5215d7dc739b1301fdadc3926740d6f
cd $GITROOT/phet-io-wrappers; git checkout f49272efdfbd0ee0618c8037c6020acc2acf2344
cd $GITROOT/phetcommon; git checkout 92535c7f8a9739a52821269939d4b39d4e2d8e2d
cd $GITROOT/phetmarks; git checkout 60b91aac6da08b85ea47aec991c666ed4c6bcc6b
cd $GITROOT/query-string-machine; git checkout 5fbbd97d38c2b32506ad3e711e18832dd85ce28e
cd $GITROOT/scenery; git checkout 27d7d5610f59eaed60d484ae7d86fac93398a4fe
cd $GITROOT/scenery-phet; git checkout b491faff4bed411f7a1576961e47245f593f96cb
cd $GITROOT/sherpa; git checkout aa4b6a75a6eacf1cf5945092d5425fd2f7cb4d77
cd $GITROOT/studio; git checkout ea41b45429265bf5a2a8946334cf33b12a97480b
cd $GITROOT/sun; git checkout 60157164fb777b94392b0fc38219f1bc7350195e
cd $GITROOT/tambo; git checkout bf81ff4f98d96731eda2b707b8cfb422ce4de3cf
cd $GITROOT/tandem; git checkout dab2b00aa2515ada2dbf95c9fea3665042b24569
cd $GITROOT/twixt; git checkout 0f3b8ac8e973c12bd9b9ce30e1e583bb1bf4cd84
cd $GITROOT/unit-rates; git checkout aa5452383eca58eb653e0d4c56cd5caff2a4bc7d
cd $GITROOT/utterance-queue; git checkout 3e4f9e8d9767b86b6b0cc0c8ba57f82fe3dd16ab
```

</details>

**Comment by pixelzoom** [comment]
I applied the same console.log patch to DoubleNumberLineAccordionBox.ts in 1.1.0-dev.6, followed the steps in https://github.com/phetsims/unit-rates/issues/232#issuecomment-2430447696, and I got very different console output, a very different order:

> 1. numerator changed, null => 2
> 2. before resetting markerEditor 2/5
> 3. numerator changed, 2 => null
> 4. denominator changed, 5 => null
> 5. after resetting markerEditor null/null
> 6. setting undoMarker Marker[ rate=2/5 creator=editor isMajor=true erasable=true ]
> 7. denominator changed, null => 5

Note that numerator and denominator listeners (lines 3 & 4) are now executing when expected, before setting the undo marker (line 5).

So something about axon notification has changed, smells like a regression, and I'll need to discuss with @zepumph and/or @samreid.

**Comment by pixelzoom** [comment]
There were 89 commits to axon between 2/13/24 and 7/5/24.   I guess I'll start applying them to the axon sha for unit-rates 1.1.0-dev.6, and see where the behavior change occurs.

**Comment by pixelzoom** [comment]
Wow, I got lucky!  89 commits to investigate, and the first commit that I applied (https://github.com/phetsims/axon/commit/77bb748db78c625d8154be852fe5e503177c1779 from 2/13) breaks my sim.  That commit was for https://github.com/phetsims/axon/issues/447, and it changes the default behavior of Emitters and Properties. There are now 'queue' and 'stack' strategies for reentry, and default behavior was changed from 'stack' to 'queue'.

**Comment by pixelzoom** [comment]
So... The default reentry behavior for TinyEmitter (and therefore for Property) was changed from 'stack' to 'queue', and the implementation of `markerObserver` in DoubleNumberLineAccordionBox is relying on 'stack' behavor.  (Read about 'stack' vs 'queue' in TinyEmitter, `type ReentrantNotificationStrategy`.)

The patch below fixes the problem in unit-rates. It involves adding 2 lines of code, to specify `reentrantNotificationStrategy: 'stack'` for MarkerEditor's `numeratorProperty` and `denominatorProperty`.   

I'll need to discuss this with @zepumph via Zoom. I'd like to understand the problem that was being addressed in https://github.com/phetsims/axon/issues/447, why the default was changed, and make sure that using `reentrantNotificationStrategy: 'stack'` is not going to be a problem in this specific case. I'm also wondering how many other subtle (expensive) regressions this change might have introduced.

```ts
Subject: [PATCH] workaround for https://github.com/phetsims/sun/issues/904
---
Index: js/common/model/MarkerEditor.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/MarkerEditor.ts b/js/common/model/MarkerEditor.ts
--- a/js/common/model/MarkerEditor.ts	(revision 4346868ad9d6fc97e307eb7ff3f999328ca82d3e)
+++ b/js/common/model/MarkerEditor.ts	(date 1729723998138)
@@ -31,10 +31,12 @@
     this.denominatorAxis = denominatorAxis;
 
     this.numeratorProperty = new Property<number | null>( null, {
+      reentrantNotificationStrategy: 'stack',
       reentrant: true // see https://github.com/phetsims/unit-rates/issues/216
     } );
 
     this.denominatorProperty = new Property<number | null>( null, {
+      reentrantNotificationStrategy: 'stack',
       reentrant: true // see https://github.com/phetsims/unit-rates/issues/216
     } );
 ```

**Comment by pixelzoom** [comment]
Fixed in main and 1.1 branches.

@Nancy-Salpepi please verify in main.  If it looks OK, change the label to fixed-awaiting-deploy.

**Comment by Nancy-Salpepi** [comment]
Pulled a bunch of times on main, but I still see the bug....

**Comment by pixelzoom** [comment]
Sorry @Nancy-Salpepi. It looks like phettest is currently not in-sync with main, due to changes to build tools.  @zepumph is on the case. I'll let you know when that problem is resolved, and ready for another attempt at revieiwng.

**Comment by pixelzoom** [comment]
@zepumph says that phettest is back, and I've confirmed.  @Nancy-Salpepi would you please attempt verification again? Sorry for the inconvenience.

**Comment by Nancy-Salpepi** [comment]
Looks good!

**Comment by pixelzoom** [comment]
Ready for testing in https://github.com/phetsims/qa/issues/1158 for 1.1.0-rc.2.  It is sufficent to verify on 1 platform. Close if OK.

**Comment by KatieWoe** [comment]
Things look good in rc.2
